### ISSUE TITLE
[friend]:Echocbx

### ISSUE THREAD

**Issue by Ezgx** [GC-ZF/Comment-Backups#2]
### 网站运行了多长时间？ || How long has the site been up and running?

三个月 || three month

### 什么类型的博客 || What kind of blog?

都有

### 填写友链 || input your blog information?

 每个字段前请保留空格 
 ```yml 
 name: Echocbx
 link: http://ezgx.tk
 avatar: https://ezgx.tk/img/avatar.png 
 descr: 分享科技与很活 
 ```
