### ISSUE TITLE
[friend]:https://blog.bornforthis.cn

### ISSUE THREAD

**Issue by AndersonHJB** [GC-ZF/Comment-Backups#4]
### 网站运行了多长时间？ || How long has the site been up and running?

新建没多久 || just soon

### 什么类型的博客 || What kind of blog?

技术栈

### 填写友链 || input your blog information?

 每个字段前请保留空格 
 ```yml 
- name: AI悦创
  link: https://blog.bornforthis.cn
  avatar: https://bornforthis.cn/aiyc.svg
  descr: AI悦创·创造不同～
  siteshot: https://blog.bornforthis.cn/img/link/00-blog.bornforthis.cn.png
 ```
 
额外：你网站怎么全部编程灰色了？
